CREATE USER C##ntg IDENTIFIED BY NTGasdf1234;



GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE SYNONYM, CREATE CLUSTER, CREATE DATABASE LINK, CREATE SESSION, ALTER SESSION TO C##test;



show con_name


grant unlimited tablespace to c##test;


CREATE USER C##test IDENTIFIED BY cccCCC111;


select * from c##tagan.hello




GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE SYNONYM, CREATE CLUSTER, CREATE DATABASE LINK, CREATE SESSION, ALTER SESSION TO C##ntg;


GRANT dba to c##tagan
